export const COUNTRY_MAP = {
    'af': { vi: 'Afghanistan', en: 'Afghanistan' },
    'al': { vi: 'Albania', en: 'Albania' },
    'dz': { vi: 'Algeria', en: 'Algeria' },
    'as': { vi: 'Samoa thuộc Mỹ', en: 'American Samoa' },
    'ad': { vi: 'Andorra', en: 'Andorra' },
    'ao': { vi: 'Angola', en: 'Angola' },
    'ai': { vi: 'Anguilla', en: 'Anguilla' },
    'ag': { vi: 'Antigua và Barbuda', en: 'Antigua and Barbuda' },
    'ar': { vi: 'Argentina', en: 'Argentina' },
    'am': { vi: 'Armenia', en: 'Armenia' },
    'aw': { vi: 'Aruba', en: 'Aruba' },
    'au': { vi: 'Australia', en: 'Australia' },
    'at': { vi: 'Áo', en: 'Austria' },
    'az': { vi: 'Azerbaijan', en: 'Azerbaijan' },
    'bs': { vi: 'Bahamas', en: 'Bahamas' },
    'bh': { vi: 'Bahrain', en: 'Bahrain' },
    'bd': { vi: 'Bangladesh', en: 'Bangladesh' },
    'bb': { vi: 'Barbados', en: 'Barbados' },
    'by': { vi: 'Belarus', en: 'Belarus' },
    'be': { vi: 'Bỉ', en: 'Belgium' },
    'bz': { vi: 'Belize', en: 'Belize' },
    'bj': { vi: 'Benin', en: 'Benin' },
    'bm': { vi: 'Bermuda', en: 'Bermuda' },
    'bt': { vi: 'Bhutan', en: 'Bhutan' },
    'bo': { vi: 'Bolivia', en: 'Bolivia' },
    'ba': { vi: 'Bosnia và Herzegovina', en: 'Bosnia and Herzegovina' },
    'bw': { vi: 'Botswana', en: 'Botswana' },
    'br': { vi: 'Brazil', en: 'Brazil' },
    'vg': { vi: 'Quần đảo Virgin thuộc Anh', en: 'British Virgin Islands' },
    'bn': { vi: 'Brunei', en: 'Brunei' },
    'bg': { vi: 'Bulgaria', en: 'Bulgaria' },
    'bf': { vi: 'Burkina Faso', en: 'Burkina Faso' },
    'bi': { vi: 'Burundi', en: 'Burundi' },
    'kh': { vi: 'Campuchia', en: 'Cambodia' },
    'cm': { vi: 'Cameroon', en: 'Cameroon' },
    'ca': { vi: 'Canada', en: 'Canada' },
    'cv': { vi: 'Cape Verde', en: 'Cape Verde' },
    'ky': { vi: 'Quần đảo Cayman', en: 'Cayman Islands' },
    'cf': { vi: 'Cộng hòa Trung Phi', en: 'Central African Republic' },
    'td': { vi: 'Chad', en: 'Chad' },
    'cl': { vi: 'Chile', en: 'Chile' },
    'cn': { vi: 'Trung Quốc', en: 'China' },
    'co': { vi: 'Colombia', en: 'Colombia' },
    'km': { vi: 'Comoros', en: 'Comoros' },
    'cg': { vi: 'Congo', en: 'Congo' },
    'ck': { vi: 'Quần đảo Cook', en: 'Cook Islands' },
    'cr': { vi: 'Costa Rica', en: 'Costa Rica' },
    'hr': { vi: 'Croatia', en: 'Croatia' },
    'cu': { vi: 'Cuba', en: 'Cuba' },
    'cy': { vi: 'Síp', en: 'Cyprus' },
    'cz': { vi: 'Cộng hòa Séc', en: 'Czech Republic' },
    'cd': { vi: 'CHDC Congo', en: 'DR Congo' },
    'dk': { vi: 'Đan Mạch', en: 'Denmark' },
    'dj': { vi: 'Djibouti', en: 'Djibouti' },
    'dm': { vi: 'Dominica', en: 'Dominica' },
    'do': { vi: 'Cộng hòa Dominica', en: 'Dominican Republic' },
    'ec': { vi: 'Ecuador', en: 'Ecuador' },
    'eg': { vi: 'Ai Cập', en: 'Egypt' },
    'sv': { vi: 'El Salvador', en: 'El Salvador' },
    'eng': { vi: 'Anh', en: 'England' }, // Special for soccer
    'en': { vi: 'Anh', en: 'England' },
    'gq': { vi: 'Guinea Xích đạo', en: 'Equatorial Guinea' },
    'er': { vi: 'Eritrea', en: 'Eritrea' },
    'ee': { vi: 'Estonia', en: 'Estonia' },
    'sz': { vi: 'Eswatini', en: 'Eswatini' },
    'et': { vi: 'Ethiopia', en: 'Ethiopia' },
    'fo': { vi: 'Quần đảo Faroe', en: 'Faroe Islands' },
    'fj': { vi: 'Fiji', en: 'Fiji' },
    'fi': { vi: 'Phần Lan', en: 'Finland' },
    'fr': { vi: 'Pháp', en: 'France' },
    'ga': { vi: 'Gabon', en: 'Gabon' },
    'gm': { vi: 'Gambia', en: 'Gambia' },
    'ge': { vi: 'Georgia', en: 'Georgia' },
    'de': { vi: 'Đức', en: 'Germany' },
    'gh': { vi: 'Ghana', en: 'Ghana' },
    'gi': { vi: 'Gibraltar', en: 'Gibraltar' },
    'gr': { vi: 'Hy Lạp', en: 'Greece' },
    'gl': { vi: 'Greenland', en: 'Greenland' },
    'gd': { vi: 'Grenada', en: 'Grenada' },
    'gu': { vi: 'Guam', en: 'Guam' },
    'gt': { vi: 'Guatemala', en: 'Guatemala' },
    'gn': { vi: 'Guinea', en: 'Guinea' },
    'gw': { vi: 'Guinea-Bissau', en: 'Guinea-Bissau' },
    'gy': { vi: 'Guyana', en: 'Guyana' },
    'ht': { vi: 'Haiti', en: 'Haiti' },
    'hn': { vi: 'Honduras', en: 'Honduras' },
    'hk': { vi: 'Hồng Kông', en: 'Hong Kong' },
    'hu': { vi: 'Hungary', en: 'Hungary' },
    'is': { vi: 'Iceland', en: 'Iceland' },
    'in': { vi: 'Ấn Độ', en: 'India' },
    'id': { vi: 'Indonesia', en: 'Indonesia' },
    'ir': { vi: 'Iran', en: 'Iran' },
    'iq': { vi: 'Iraq', en: 'Iraq' },
    'ie': { vi: 'Ireland', en: 'Ireland' },
    'il': { vi: 'Israel', en: 'Israel' },
    'it': { vi: 'Ý', en: 'Italy' },
    'ci': { vi: 'Bờ Biển Ngà', en: 'Ivory Coast' },
    'jm': { vi: 'Jamaica', en: 'Jamaica' },
    'jp': { vi: 'Nhật Bản', en: 'Japan' },
    'jo': { vi: 'Jordan', en: 'Jordan' },
    'kz': { vi: 'Kazakhstan', en: 'Kazakhstan' },
    'ke': { vi: 'Kenya', en: 'Kenya' },
    'ki': { vi: 'Kiribati', en: 'Kiribati' },
    'xk': { vi: 'Kosovo', en: 'Kosovo' },
    'kw': { vi: 'Kuwait', en: 'Kuwait' },
    'kg': { vi: 'Kyrgyzstan', en: 'Kyrgyzstan' },
    'la': { vi: 'Lào', en: 'Laos' },
    'lv': { vi: 'Latvia', en: 'Latvia' },
    'lb': { vi: 'Liban', en: 'Lebanon' },
    'ls': { vi: 'Lesotho', en: 'Lesotho' },
    'lr': { vi: 'Liberia', en: 'Liberia' },
    'ly': { vi: 'Libya', en: 'Libya' },
    'li': { vi: 'Liechtenstein', en: 'Liechtenstein' },
    'lt': { vi: 'Litva', en: 'Lithuania' },
    'lu': { vi: 'Luxembourg', en: 'Luxembourg' },
    'mo': { vi: 'Macao', en: 'Macau' },
    'mg': { vi: 'Madagascar', en: 'Madagascar' },
    'mw': { vi: 'Malawi', en: 'Malawi' },
    'my': { vi: 'Malaysia', en: 'Malaysia' },
    'mv': { vi: 'Maldives', en: 'Maldives' },
    'ml': { vi: 'Mali', en: 'Mali' },
    'mt': { vi: 'Malta', en: 'Malta' },
    'mh': { vi: 'Quần đảo Marshall', en: 'Marshall Islands' },
    'mr': { vi: 'Mauritanie', en: 'Mauritania' },
    'mu': { vi: 'Mauritius', en: 'Mauritius' },
    'mx': { vi: 'Mexico', en: 'Mexico' },
    'fm': { vi: 'Micronesia', en: 'Micronesia' },
    'md': { vi: 'Moldova', en: 'Moldova' },
    'mc': { vi: 'Monaco', en: 'Monaco' },
    'mn': { vi: 'Mông Cổ', en: 'Mongolia' },
    'me': { vi: 'Montenegro', en: 'Montenegro' },
    'ms': { vi: 'Montserrat', en: 'Montserrat' },
    'ma': { vi: 'Ma-rốc', en: 'Morocco' },
    'mz': { vi: 'Mozambique', en: 'Mozambique' },
    'mm': { vi: 'Myanmar', en: 'Myanmar' },
    'na': { vi: 'Namibia', en: 'Namibia' },
    'nr': { vi: 'Nauru', en: 'Nauru' },
    'np': { vi: 'Nepal', en: 'Nepal' },
    'nl': { vi: 'Hà Lan', en: 'Netherlands' },
    'nc': { vi: 'New Caledonia', en: 'New Caledonia' },
    'nz': { vi: 'New Zealand', en: 'New Zealand' },
    'ni': { vi: 'Nicaragua', en: 'Nicaragua' },
    'ne': { vi: 'Niger', en: 'Niger' },
    'ng': { vi: 'Nigeria', en: 'Nigeria' },
    'kp': { vi: 'Triều Tiên', en: 'North Korea' },
    'mk': { vi: 'Bắc Macedonia', en: 'North Macedonia' },
    'no': { vi: 'Na Uy', en: 'Norway' },
    'om': { vi: 'Oman', en: 'Oman' },
    'pk': { vi: 'Pakistan', en: 'Pakistan' },
    'pw': { vi: 'Palau', en: 'Palau' },
    'ps': { vi: 'Palestine', en: 'Palestine' },
    'pa': { vi: 'Panama', en: 'Panama' },
    'pg': { vi: 'Papua New Guinea', en: 'Papua New Guinea' },
    'py': { vi: 'Paraguay', en: 'Paraguay' },
    'pe': { vi: 'Peru', en: 'Peru' },
    'ph': { vi: 'Philippines', en: 'Philippines' },
    'pl': { vi: 'Ba Lan', en: 'Poland' },
    'pt': { vi: 'Bồ Đào Nha', en: 'Portugal' },
    'pr': { vi: 'Puerto Rico', en: 'Puerto Rico' },
    'qa': { vi: 'Qatar', en: 'Qatar' },
    're': { vi: 'Réunion', en: 'Réunion' },
    'ro': { vi: 'Romania', en: 'Romania' },
    'ru': { vi: 'Nga', en: 'Russia' },
    'rw': { vi: 'Rwanda', en: 'Rwanda' },
    'kn': { vi: 'Saint Kitts và Nevis', en: 'Saint Kitts and Nevis' },
    'lc': { vi: 'Saint Lucia', en: 'Saint Lucia' },
    'vc': { vi: 'Saint Vincent và Grenadines', en: 'Saint Vincent and the Grenadines' },
    'ws': { vi: 'Samoa', en: 'Samoa' },
    'sm': { vi: 'San Marino', en: 'San Marino' },
    'st': { vi: 'Sao Tome và Principe', en: 'Sao Tome and Principe' },
    'sa': { vi: 'Ả Rập Xê-út', en: 'Saudi Arabia' },
    'scotland': { vi: 'Scotland', en: 'Scotland' },
    'sn': { vi: 'Senegal', en: 'Senegal' },
    'rs': { vi: 'Serbia', en: 'Serbia' },
    'sc': { vi: 'Seychelles', en: 'Seychelles' },
    'sl': { vi: 'Sierra Leone', en: 'Sierra Leone' },
    'sg': { vi: 'Singapore', en: 'Singapore' },
    'sk': { vi: 'Slovakia', en: 'Slovakia' },
    'si': { vi: 'Slovenia', en: 'Slovenia' },
    'sb': { vi: 'Quần đảo Solomon', en: 'Solomon Islands' },
    'so': { vi: 'Somalia', en: 'Somalia' },
    'za': { vi: 'Nam Phi', en: 'South Africa' },
    'kr': { vi: 'Hàn Quốc', en: 'South Korea' },
    'ss': { vi: 'Nam Sudan', en: 'South Sudan' },
    'es': { vi: 'Tây Ban Nha', en: 'Spain' },
    'lk': { vi: 'Sri Lanka', en: 'Sri Lanka' },
    'sd': { vi: 'Sudan', en: 'Sudan' },
    'sr': { vi: 'Suriname', en: 'Suriname' },
    'se': { vi: 'Thụy Điển', en: 'Sweden' },
    'ch': { vi: 'Thụy Sĩ', en: 'Switzerland' },
    'sy': { vi: 'Syria', en: 'Syria' },
    'tw': { vi: 'Đài Loan', en: 'Taiwan' },
    'tj': { vi: 'Tajikistan', en: 'Tajikistan' },
    'tz': { vi: 'Tanzania', en: 'Tanzania' },
    'th': { vi: 'Thái Lan', en: 'Thailand' },
    'tl': { vi: 'Timor-Leste', en: 'Timor-Leste' },
    'tg': { vi: 'Togo', en: 'Togo' },
    'to': { vi: 'Tonga', en: 'Tonga' },
    'tt': { vi: 'Trinidad và Tobago', en: 'Trinidad and Tobago' },
    'tn': { vi: 'Tunisia', en: 'Tunisia' },
    'tr': { vi: 'Thổ Nhĩ Kỳ', en: 'Turkey' },
    'tm': { vi: 'Turkmenistan', en: 'Turkmenistan' },
    'tv': { vi: 'Tuvalu', en: 'Tuvalu' },
    'ug': { vi: 'Uganda', en: 'Uganda' },
    'ua': { vi: 'Ukraine', en: 'Ukraine' },
    'ae': { vi: 'UAE', en: 'United Arab Emirates' },
    'gb': { vi: 'Vương quốc Anh', en: 'United Kingdom' },
    'us': { vi: 'Hoa Kỳ', en: 'USA' },
    'uy': { vi: 'Uruguay', en: 'Uruguay' },
    'uz': { vi: 'Uzbekistan', en: 'Uzbekistan' },
    'vu': { vi: 'Vanuatu', en: 'Vanuatu' },
    've': { vi: 'Venezuela', en: 'Venezuela' },
    'vn': { vi: 'Việt Nam', en: 'Vietnam' },
    'wales': { vi: 'Wales', en: 'Wales' },
    'ye': { vi: 'Yemen', en: 'Yemen' },
    'zm': { vi: 'Zambia', en: 'Zambia' },
    'zw': { vi: 'Zimbabwe', en: 'Zimbabwe' },
};

export const getCountryNames = (natString) => {
    if (!natString) return { vi: 'N/A', en: 'N/A' };
    
    // Format is usually "xx XXX" (e.g. "vn VNM")
    const code = natString.split(' ')[0].toLowerCase();
    
    if (COUNTRY_MAP[code]) {
        return COUNTRY_MAP[code];
    }
    
    // If not in map, return the raw code uppercase
    const raw = code.toUpperCase();
    return { vi: raw, en: raw };
};

export const getFullDisplay = (natString) => {
    const names = getCountryNames(natString);
    return names.vi;
};
